[package]
name = "starlark_bin"
edition = "2021"
version = "0.10.0"
license = "Apache-2.0"
description = "starlark binary"
documentation = "https://docs.rs/starlark"
repository = "https://github.com/facebookexperimental/starlark-rust"
authors = [
    "Damien Martin-Guillerez <dmarting@google.com>",
    "Facebook",
]
keywords = ["starlark", "skylark", "language", "interpreter"]
categories = ["parser-implementations", "development-tools"]

[dependencies]
dupe = { workspace = true }

starlark = { version = "0.10.0", path = "../starlark" }
starlark_lsp = { version = "0.10.0", path = "../starlark_lsp" }
starlark_map = { version = "0.10.0", path = "../starlark_map" }

anyhow = "1.0.65"
argfile = "0.1.0"
clap = { version = "4.0.7", features = ["derive", "wrap_help"] }
debugserver-types = "0.5.0"
either = "1.8"
itertools = "0.10"
lsp-types = "0.94.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.36"
walkdir = "2.3"

[[bin]]
name = "starlark"
path = "bin/main.rs"
